Word2vec lstm
Yoctol/seq2vec pull request #14
Opened 2017-03-15 06:16 UTC by plliao

WIP

2017-03-15 06:51 UTC, plliao commented
I guess I can extract DataGenerator as a generator to support all seq2vec model

2017-03-15 06:59 UTC, stegben requested changes
generator 相關的應該要額外獨立成一個檔案，而不是寫在 class 裡面，另外也請加 example 到 README

2017-03-15 06:59 UTC, stegben commented on seq2vec/seq2seq_word2vec.py
> +            model_path,
命名可能要修一下，這樣不曉得是什麼的 model

2017-03-15 06:59 UTC, stegben commented on seq2vec/seq2seq_word2vec.py
> +        self.model_general = KeyedVectors.load_word2vec_format(
`model_general` 一樣是個有點模糊的命名

2017-03-15 06:59 UTC, stegben commented on seq2vec/seq2seq_word2vec.py
> +    def my_generator(self, train_seqs, test_seqs):
`my_generator` 命名再具體一點，是什麼的 generator

2017-03-15 06:59 UTC, stegben commented on seq2vec/seq2seq_word2vec.py
> +                    with open(predict_file_path, 'r', encoding='utf-8') as test_file:
不用這樣巢狀，如下即可，否則 code 太多 indent 了
```python
with open('a'), open('b') as f_a, f_b:
    ...
```

2017-03-15 06:59 UTC, stegben commented on seq2vec/seq2seq_word2vec.py
> +                train_file.close()
redundant

2017-03-15 06:59 UTC, stegben commented on seq2vec/seq2seq_word2vec.py
> +                test_file.close()
These are redundant

2017-03-15 06:59 UTC, stegben commented on seq2vec/seq2seq_word2vec.py
> +        while True:
這個 while 的用處是？

2017-03-15 08:18 UTC, plliao commented
generator已經拉出來了, 另外加了transfomer, 你可以快速看看這樣的架構ok不ok

2017-03-16 08:21 UTC, plliao commented
我把seq2vec auto encoder 和 word2vec兩個class 相同的function搬到base裡了， @stegben 你看看這樣寫好不好

2017-03-17 02:39 UTC, stegben approved these changes

2017-03-17 02:39 UTC, merged